### ISSUE TITLE
Package still detected as redundant *after* it has been "nolyfilled"

### ISSUE THREAD

**Issue by wojtekmaj** [SukkaW/nolyfill#37]
<img width="1178" alt="image" src="https://github.com/SukkaW/nolyfill/assets/5426427/b3b4c700-f69e-4e7e-bb8f-4d68b0d17e2b">

**Comment by SukkaW** [comment]
This is a known issue caused by the current `yarn.lock` parsing mechanism, which relies on fragile assumptions.

**Comment by wojtekmaj** [comment]
I think I know where this error is coming from. I've added a couple of console.logs:

```
Diving to createPackageNode from jsx-ast-utils dependencies level:
 { depName: 'object.assign', depVersion: '^4.1.3' }

Setting to referenceMap:
 object.assign { name: 'object.assign', version: '^4.1.3', dependencies: [] }

Diving to createPackageNode from top level: { depName: 'object.assign', depVersion: '1.0.21' }

referenceMap already has object.assign :
 { name: 'object.assign', version: '^4.1.3', dependencies: [] } 
so will not store:
 {
  name: '@nolyfill/object.assign',
  version: '1.0.21',
  dependencies: []
}

Found 1 redundant packages:
 object.assign ^4.1.3
```

So in my case, we're first hitting entry for `jsx-ast-utils` in the lockfile:

```
"jsx-ast-utils@npm:^2.4.1 || ^3.0.0, jsx-ast-utils@npm:^3.3.3":
  version: 3.3.3
  resolution: "jsx-ast-utils@npm:3.3.3"
  dependencies:
    array-includes: ^3.1.5
    object.assign: ^4.1.3
  checksum: a2ed78cac49a0f0c4be8b1eafe3c5257a1411341d8e7f1ac740debae003de04e5f6372bfcfbd9d082e954ffd99aac85bcda85b7c6bc11609992483f4cdc0f745
  languageName: node
  linkType: hard
```

This provides information of object.assign@npm:^4.1.3 existing, but NOT about it being already nolyfilled. Then, when it gets to _actual_ top-level object.assign entry, it skips storing it in the referenceMap because "it already has it".

Then I thought to myself, why do we even care about dependencies, if all entries of Yarn lockfile are top-level?

So I removed this bit:

https://github.com/SukkaW/nolyfill/blob/2106f9b09c5dc8b4f4b1111ab8f8072207e75e24/packages/tools/cli/src/lockfile/yarn.ts#L52-L54

and everything worked like a charm, AND a bit faster too. The final list of resolutions was still overly large (#36), but this issue was gone:

```
Diving to createPackageNode from top level: { depName: 'object.assign', depVersion: '1.0.21' }

Setting to referenceMap:
 object.assign {
  name: '@nolyfill/object.assign',
  version: '1.0.21',
  dependencies: []
}
Congratulations! Your project does not contain any redundant polyfills that can be optimized by nolyfill 🚀
```
